var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <array>"},
{"lineNum":"    4","line":"#include <concepts>"},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"#include <magic_enum/magic_enum.hpp>"},
{"lineNum":"    7","line":""},
{"lineNum":"    8","line":"#include \"stdx/type_traits.hh\""},
{"lineNum":"    9","line":"#include \"stdx/types.hh\""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"namespace stdx {"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"using magic_enum::enum_value;"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"// Returns the minimum value of the present enumerations as the value"},
{"lineNum":"   16","line":"template <Enum E> consteval auto enum_min_value() { return enum_value<E>(0); }"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":"// Returns the minimum value of the present enumerations as the underlying value"},
{"lineNum":"   19","line":"template <Enum E> consteval auto enum_min_underlying() {"},
{"lineNum":"   20","line":"    return magic_enum::enum_integer(enum_min_value<E>());"},
{"lineNum":"   21","line":"}"},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"// Returns the maximum value of the present enumerations as the value"},
{"lineNum":"   24","line":"template <Enum E> consteval auto enum_max_value() {"},
{"lineNum":"   25","line":"    return enum_value<E>(magic_enum::enum_count<E>() - 1);"},
{"lineNum":"   26","line":"}"},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"// Returns the maximum value of the present enumerations as the underlying value"},
{"lineNum":"   29","line":"template <Enum E> consteval auto enum_max_underlying() {"},
{"lineNum":"   30","line":"    return magic_enum::enum_integer(enum_max_value<E>());"},
{"lineNum":"   31","line":"}"},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"// Requires that the enum is in an exclusively bounded range of magic enum bounds"},
{"lineNum":"   34","line":"//"},
{"lineNum":"   35","line":"// This prevents possible bugs and should be fixed by adjusting defines in `build.zig`"},
{"lineNum":"   36","line":"template <typename E>"},
{"lineNum":"   37","line":"concept BoundedEnum = Enum<E> && requires {"},
{"lineNum":"   38","line":"    enum_min_underlying<E>() > MAGIC_ENUM_RANGE_MIN &&"},
{"lineNum":"   39","line":"        enum_max_underlying<E>() < MAGIC_ENUM_RANGE_MAX;"},
{"lineNum":"   40","line":"};"},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"// Returns an inclusive range of enum values. Requires `lower < higher`"},
{"lineNum":"   43","line":"template <auto Lower, auto Upper>"},
{"lineNum":"   44","line":"    requires(BoundedEnum<decltype(Lower)> && std::same_as<decltype(Lower), decltype(Upper)>)"},
{"lineNum":"   45","line":"consteval auto enum_range() noexcept {"},
{"lineNum":"   46","line":"    using enum_type = decltype(Lower);"},
{"lineNum":"   47","line":"    constexpr auto opt_low{magic_enum::enum_index<enum_type>(Lower)};"},
{"lineNum":"   48","line":"    constexpr auto opt_high{magic_enum::enum_index<enum_type>(Upper)};"},
{"lineNum":"   49","line":"    static_assert(opt_low && opt_high, \"Bounds must be valid enumerations\");"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"    constexpr usize low_idx{*opt_low};"},
{"lineNum":"   52","line":"    constexpr usize high_idx{*opt_high};"},
{"lineNum":"   53","line":"    static_assert(high_idx >= low_idx, \"Range must be strictly increasing\");"},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"    // The range is inclusive to circumvent weird indexing"},
{"lineNum":"   56","line":"    constexpr usize              count{high_idx - low_idx + 1};"},
{"lineNum":"   57","line":"    std::array<enum_type, count> range;"},
{"lineNum":"   58","line":"    for (usize i{0}; i < range.size(); ++i) { range[i] = enum_value<enum_type>(low_idx + i); }"},
{"lineNum":"   59","line":"    return range;"},
{"lineNum":"   60","line":"}"},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"// Returns an array of all possible enum values"},
{"lineNum":"   63","line":"template <BoundedEnum E> consteval auto enum_range() noexcept {"},
{"lineNum":"   64","line":"    return enum_range<enum_min_value<E>(), enum_max_value<E>()>();"},
{"lineNum":"   65","line":"}"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"namespace enum_ops {"},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator++(E& e) noexcept -> E {","class":"lineCov","hits":"1","order":"347",},
{"lineNum":"   70","line":"    e = static_cast<E>(std::to_underlying(e) + 1);","class":"lineCov","hits":"1","order":"340",},
{"lineNum":"   71","line":"    return e;","class":"lineCov","hits":"1","order":"338",},
{"lineNum":"   72","line":"}"},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator++(E& e, i32) noexcept -> E {","class":"lineCov","hits":"1","order":"348",},
{"lineNum":"   75","line":"    E tmp{e};","class":"lineCov","hits":"1","order":"345",},
{"lineNum":"   76","line":"    e = static_cast<E>(std::to_underlying(e) + 1);","class":"lineCov","hits":"1","order":"343",},
{"lineNum":"   77","line":"    return tmp;","class":"lineCov","hits":"1","order":"341",},
{"lineNum":"   78","line":"}"},
{"lineNum":"   79","line":""},
{"lineNum":"   80","line":"template <ScopedEnum E> constexpr auto operator|(E lhs, E rhs) -> E {","class":"lineCov","hits":"1","order":"346",},
{"lineNum":"   81","line":"    return static_cast<E>(std::to_underlying(lhs) | std::to_underlying(rhs));","class":"lineCov","hits":"1","order":"339",},
{"lineNum":"   82","line":"}"},
{"lineNum":"   83","line":""},
{"lineNum":"   84","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator|=(E& lhs, E rhs) -> E& {"},
{"lineNum":"   85","line":"    lhs = lhs | rhs;"},
{"lineNum":"   86","line":"    return lhs;"},
{"lineNum":"   87","line":"}"},
{"lineNum":"   88","line":""},
{"lineNum":"   89","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator&(E lhs, E rhs) -> E {","class":"lineCov","hits":"1","order":"337",},
{"lineNum":"   90","line":"    return static_cast<E>(std::to_underlying(lhs) & std::to_underlying(rhs));","class":"lineCov","hits":"1","order":"336",},
{"lineNum":"   91","line":"}"},
{"lineNum":"   92","line":""},
{"lineNum":"   93","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator&=(E& lhs, E rhs) -> E& {"},
{"lineNum":"   94","line":"    lhs = lhs & rhs;"},
{"lineNum":"   95","line":"    return lhs;"},
{"lineNum":"   96","line":"}"},
{"lineNum":"   97","line":""},
{"lineNum":"   98","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator^(E lhs, E rhs) -> E {","class":"lineCov","hits":"1","order":"344",},
{"lineNum":"   99","line":"    return static_cast<E>(std::to_underlying(lhs) ^ std::to_underlying(rhs));","class":"lineCov","hits":"1","order":"342",},
{"lineNum":"  100","line":"}"},
{"lineNum":"  101","line":""},
{"lineNum":"  102","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator^=(E& lhs, E rhs) -> E& {"},
{"lineNum":"  103","line":"    lhs = lhs ^ rhs;"},
{"lineNum":"  104","line":"    return lhs;"},
{"lineNum":"  105","line":"}"},
{"lineNum":"  106","line":""},
{"lineNum":"  107","line":"template <ScopedEnum E> [[nodiscard]] constexpr auto operator~(E op) -> E {","class":"lineCov","hits":"1","order":"335",},
{"lineNum":"  108","line":"    return static_cast<E>(~std::to_underlying(op));","class":"lineCov","hits":"1","order":"334",},
{"lineNum":"  109","line":"}"},
{"lineNum":"  110","line":""},
{"lineNum":"  111","line":"} // namespace enum_ops"},
{"lineNum":"  112","line":""},
{"lineNum":"  113","line":"// NOLINTBEGIN"},
{"lineNum":"  114","line":"#define MAKE_ENUM_OPERATORS(EnumType)                                                    \\"},
{"lineNum":"  115","line":"    constexpr auto operator|(EnumType lhs, EnumType rhs)->EnumType {                     \\"},
{"lineNum":"  116","line":"        return static_cast<EnumType>(std::to_underlying(lhs) | std::to_underlying(rhs)); \\"},
{"lineNum":"  117","line":"    }                                                                                    \\"},
{"lineNum":"  118","line":"                                                                                         \\"},
{"lineNum":"  119","line":"    constexpr auto operator&(EnumType lhs, EnumType rhs)->EnumType {                     \\"},
{"lineNum":"  120","line":"        return static_cast<EnumType>(std::to_underlying(lhs) & std::to_underlying(rhs)); \\"},
{"lineNum":"  121","line":"    }                                                                                    \\"},
{"lineNum":"  122","line":"                                                                                         \\"},
{"lineNum":"  123","line":"    constexpr auto operator^(EnumType lhs, EnumType rhs)->EnumType {                     \\"},
{"lineNum":"  124","line":"        return static_cast<EnumType>(std::to_underlying(lhs) ^ std::to_underlying(rhs)); \\"},
{"lineNum":"  125","line":"    }                                                                                    \\"},
{"lineNum":"  126","line":"                                                                                         \\"},
{"lineNum":"  127","line":"    constexpr auto operator|=(EnumType& lhs, EnumType rhs)->EnumType& {                  \\"},
{"lineNum":"  128","line":"        lhs = lhs | rhs;                                                                 \\"},
{"lineNum":"  129","line":"        return lhs;                                                                      \\"},
{"lineNum":"  130","line":"    }                                                                                    \\"},
{"lineNum":"  131","line":"                                                                                         \\"},
{"lineNum":"  132","line":"    constexpr auto operator~(EnumType op)->EnumType {                                    \\"},
{"lineNum":"  133","line":"        return static_cast<EnumType>(~std::to_underlying(op));                           \\"},
{"lineNum":"  134","line":"    }"},
{"lineNum":"  135","line":"// NOLINTEND"},
{"lineNum":"  136","line":""},
{"lineNum":"  137","line":"} // namespace stdx"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-07-18 21:28:42", "instrumented" : 15, "covered" : 15,};
var merged_data = [];
